### ISSUE TITLE
To-do list for manuscript

### ISSUE THREAD

**Issue by asmahani** [asmahani/TextEmbeddingFE#12]
# To-do list

## Arxiv submission
- [x] Edit abstract, including replacing ??'s with actual numbers.
- [x] Absorb Table 1 (our contributions) back into the text
- [x] Edit "computing environment"
- [x] Consider adding more explanation of the CV-based approach to the section "Embedding-based Risk Score"
- [x] Regenerate figure 3: a) add numbers to bars, b) replace "MBE" with "BoC"
- [x] Review comments from Serban, Richard and Yadav on the LLM email from Mansour, and incorporate any useful quotes into the section "AI Explaining AI".
- [x] Do the same changes listed for Figure 3 to Figure 4.
- [x] Figure 5: a) add figure caption, b) add the text for "observations".
- [x] Write the "future work" subsection of Discussion.
- [x] Review with Mansour before posting to arxiv.

## Journal submission
- [ ] Add models from HuggingFace via the "sentence transformers" Python package.
- [ ] Add support in package for spherical kmeans
- [ ] Consistent use of acronyms
- [ ] Final review with Mansour and edits
- [ ] Enhance literature search
- [ ] Improve segment in Intro on "three generations of embedding models"
- [ ] Consider adding a 'regression' example (e.g. underlying continuous scores for AKI) to both the package and the manuscript.

**Comment by asmahani** [comment]
created a new issue for journal to-do's
