### ISSUE TITLE
To-do for journal submission

### ISSUE THREAD

**Issue by asmahani** [asmahani/TextEmbeddingFE#15]
### Pure manuscript
- [ ] Consistent use of acronyms
- [ ] Improve segment in Intro on "three generations of embedding models"
- [ ] Enhance literature search
- [ ] Final review with Mansour and edits

### Manuscript and software
- [ ] _Beyond binary classification_: Consider adding a 'regression' example (e.g. underlying continuous scores for AKI) to both the package and the manuscript.
- [ ] _Beyond OpenAI_: Add models from HuggingFace via the "sentence transformers" Python package.
- [ ] Add support in package for _spherical kmeans_ (not needed for manuscript only)
